# GitHub Actions工作流配置文件

name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-binary
          path: target/${{ matrix.platform }}/release/your_binary_name # 替换 your_binary_name 为你的可执行文件名称

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.platform }}-binary

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release includes binaries for the following platforms:
            - Linux
            - Windows
            - macOS
          artifacts: |
            x86_64-unknown-linux-gnu-binary
            x86_64-pc-windows-msvc-binary
            x86_64-apple-darwin-binary
